<?php

/**
 * PluginInboundEmailAttachmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginInboundEmailAttachmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginInboundEmailAttachmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginInboundEmailAttachment');
    }
}