<?php

/**
 * PluginInboundEmail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginInboundEmail extends BaseInboundEmail
{
    public static function fromMandrillEvent($mandrillApiEvent) {

        // http://help.mandrill.com/entries/22092308-what-is-the-format-of-inbound-email-webhooks
        $email = new InboundEmail();
        $email->received_at = $mandrillApiEvent->ts;
        $email->raw_msg = $mandrillApiEvent->msg->raw_msg;
        $email->text = $mandrillApiEvent->msg->text;
        $email->html = $mandrillApiEvent->msg->html;
        $email->from_email = $mandrillApiEvent->msg->from_email;
        $email->from_name = $mandrillApiEvent->msg->from_name;
        $email->recipients = $mandrillApiEvent->msg->to;
        $email->email = $mandrillApiEvent->msg->email;
        $email->subject = $mandrillApiEvent->msg->subject;

        foreach($mandrillApiEvent->msg->headers as $key => $value) {
            $header = new InboundEmailHeader();
            $header->key = $key;
            $header->value = $value;
            $email->Headers->add($header);
        }

        foreach($mandrillApiEvent->msg->attachments as $data) {
            $attachment = new InboundEmailAttachment();
            $attachment->name = $data->name;
            $attachment->mime_type = $data->type;
            $attachment->content = $data->content;
            $email->Attachments->add($attachment);
        }

        return $email;
    }
}