<?php

/**
 * PluginInboundEmailHeaderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginInboundEmailHeaderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginInboundEmailHeaderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginInboundEmailHeader');
    }
}