<?php

/**
 * PluginInboundEmailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginInboundEmailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginInboundEmailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginInboundEmail');
    }
}