<?php

/**
 * PluginOutboundEmailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOutboundEmailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginOutboundEmailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginOutboundEmail');
    }
}